version: "3"

services:
  node:
    image: node:20-alpine
    user: node
    tty: true
    stdin_open: true
    working_dir: /home/node
    env_file: .env
    command: "npm run start"
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node
